### ISSUE TITLE
Lab 4 files question

### ISSUE THREAD

**Issue by jacobtnyoung** [Watts-College/cpp-528-fall-2022#15]
In the [lab 04 tutorial](https://watts-college.github.io/cpp-528-fall-2022/labs/lab-04-tutorial.html) calls a file `labs/lab_04_source.R` that is not provided. Are we to create this file? I wasn't sure because the `labs/lab_04_source.R` file calls objects that are not created in the prior labs. Thanks!

**Comment by jacobtnyoung** [comment]
I found it here: https://github.com/Watts-College/cpp-528-fall-2022/blob/main/labs/lab_04_source.R

It was not linked to the instructions.

**Comment by castower** [comment]
Hello @jacobtnyoung,
For lab 04 you will want to pull in the listed objects that you created in Lab 03 from your utilities file. The lab_04_source.R file provides a good example of how to do this, but you'll want to note that the code is for changes from 2000-2010 and not 1990-2000. If you use that file, you will need to tweak it to have the correct years.

**Comment by jacobtnyoung** [comment]
Thanks @castower. I thought this was the case, but the [lab 04 instructions](https://watts-college.github.io/cpp-528-fall-2022/labs/lab-04-instructions.html) say "create a dataset that includes 2000 and 2010 census variables drop all rural census tracts". Are we supposed to do 1990-2000? Or, 2000-2010?

**Comment by castower** [comment]
Hi @jacobtnyoung, You're correct, I misspoke. You'll be analyzing 2000-2010 for that lab. You can just use the lab_04_source.R file as it exists. I'll update the lab to link to the file. Sorry about that!

**Comment by jacobtnyoung** [comment]
Thanks @castower !!! 🤙🏼
