### ISSUE TITLE
Custom website for project

### ISSUE THREAD

**Issue by jacobtnyoung** [Watts-College/cpp-528-fall-2022#21]
Hi @castower ! I was having difficulty setting up a theme for our project. So, I created a webpage that doesn't use a Jekyll theme. Is this ok? This problem was that it is not defaulting the the "choose theme" button on the project page. When I created the page, it did not create a config.yml file.

The page is here: https://watts-college.github.io/project-cpp-528-2022f-team-07/

I just wanted to make sure this is acceptable

**Comment by castower** [comment]
Hello @jacobtnyoung yes, that's fine. The theme is optional. 

If you'd still like to use a Jekyll theme, you can manually apply one following the steps in the GitHub theme repos that are linked on the lecture page, but that's not a requirement.

**Comment by jacobtnyoung** [comment]
Great. Thanks!

**Comment by sjone128** [comment]
@castower  Our _configure.yml file did not populate either and I'm not sure how to either create one or where to go to copy/paste it into our repo.

**Comment by castower** [comment]
Hi @sjone128, it appears the automated steps to assign a theme to Github Pages have been removed from Github. I have updated the course page with a link to an example _config.yml file that you can download and upload directly to your repository: [https://watts-college.github.io/cpp-528-fall-2022/sched/week-06/](https://watts-college.github.io/cpp-528-fall-2022/sched/week-06/) 

To change the theme, you can visit the link listed as 'Github Pages Themes Repositories', select a theme repository, and then follow the instructions in the readme to update the config file to import that theme. Let me know if you run into any issues!

**Comment by sjone128** [comment]
@castower Thank you so much!
