### ISSUE TITLE
Lab 05: Dataset for  NMTC Program Missing

### ISSUE THREAD

**Issue by sjone128** [Watts-College/cpp-528-fall-2022#23]
I was trying to get a start on Lab05 and the link to the first dataset is broken, unless I'm missing something. [Missing dataset](https://www.cdfifund.gov/news-events/news/Pages/news-detail.aspx?NewsID=364&Category=Press%20Releases)

**Comment by castower** [comment]
Hi @sjone128,
Thanks for letting us know. I'll take a look! I've been busy with a conference for work the past few days, but will get caught up on emails/reviewing the lab shortly!

**Comment by castower** [comment]
Hi @sjone128, 
The lab_05_source.R will automatically download the data for you: https://github.com/Watts-College/cpp-528-fall-2022/blob/main/labs/lab_05_source.R 

However, you can directly download them from here: 

NMTC:
https://github.com/DS4PS/cpp-528-spr-2020/blob/master/labs/data/raw/NMTC/nmtc-sheet-01.csv

LIHTC:
https://github.com/DS4PS/cpp-528-spr-2020/blob/master/labs/data/raw/LIHTC/LIHTCPUB.csv

I will update the lab page to clarify this.

**Comment by castower** [comment]
The lab page is now updated to reflect the correct links.

**Comment by sjone128** [comment]
@castower  You're the best! I hope you enjoyed the conference.
