### ISSUE TITLE
Years for final project

### ISSUE THREAD

**Issue by jacobtnyoung** [Watts-College/cpp-528-fall-2022#28]
Hi @castower! For the final project, are we to use years 2000-2010 per the [rubric](https://watts-college.github.io/cpp-528-fall-2022/project/project_rubric.html)? Or, 1990-2000. Thanks for the clarification.

**Comment by castower** [comment]
Hi Jacob, 

The dates will remain the same as they were for the labs. You don't need to make any additional changes.

**Comment by jacobtnyoung** [comment]
Thanks @castower. Happy thanksgiving! 🦃🦃🦃

**Comment by dholford** [comment]
Hey @castower, just a follow up on this:

In lab03 we were supposed to change the data to 1990 - 2000 since the tutorial was 2000 - 2010. 
In lab04 we looked at change from 2000 - 2010.

So we should have analyses for both date ranges depending on the section of the lab? Or do we use one date range?

Thanks,
Dylan

**Comment by castower** [comment]
Hi @dholford, Yes, you will have analyses for both time periods depending on the lab section.

**Comment by jacobtnyoung** [comment]
Hi @castower and @dholford   I am confused. Why would we include both 1990-2000 and 2000-2010? This seems odd as a final report structure. Seems like in the material covered in lab 3 doesnt fit the rest of the report.

Sorry, just confused on this.

**Comment by castower** [comment]
Hi @jacobtnyoung,
The overarching project is whether we can predict areas of home changes based on predictors of gentrification and/or enrollment in the tax credits programs. So for Lab 03, we created a baseline of home value changes from 1990-2000 and then we move from there to test our hypotheses for the changes we expect to see from 2000-2010.
