### ISSUE TITLE
Question about Data Steps instructions

### ISSUE THREAD

**Issue by jacobtnyoung** [Watts-College/cpp-528-fall-2022#9]
On the [Data Steps](https://watts-college.github.io/cpp-528-fall-2022/labs/PROJECT-DATA-STEPS.html) page, under the "Make two local copies of the two .R files" header, step 5 says to: 

"Select all the lines within the `labs/wk03/project_data_steps.R` and run them all to produce all of the clean data files within `data/rodeo`."

On line 16 of the `labs/wk03/project_data_steps.R` file the location is: `here::here("labs/utilities.R")`. But for the code to run, I had to set it to: `here::here("labs/wk03/utilities.R")`. That is, add `/wk03/`. I just wanted to make sure this is ok and I am not missing something.

**Comment by castower** [comment]
Hello @jacobtnyoung,
Yes, this is fine! The code references a folder system where the utilities file was stored directly under labs but it is fine to change the path to your storage location in the wk03 folder. Let me know if you have any further questions.

**Comment by jacobtnyoung** [comment]
👏🏼👏🏼👏🏼 thank you!
